title: Hubert Wonowidjojo # your name (or website title) here
logo: "/images/prof.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mahasiswa Bina Nusantara University jurusan Computer Science. Aktif dan menyukai problem solving. Member dari Jollybee Programming Team Binus. Memiliki kegiatan lain yaitu sebagai guru les dari sebuah bimbel. 
  <br><br>
  <a href="http://www.google.com">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
